data:
  folder_path: "data/raw"
  years: [2019, 2020, 2021, 2022, 2023, 2024]
  max_samples:          # Limit for faster experiments (None = use all)

split:
  val_size: 300
  test_size: 300

model:
  p_values: [0, 1, 2]
  d_values: [0, 1]
  q_values: [0, 1, 2]
  P_values: [0, 1]
  D_values: [0, 1]
  Q_values: [0, 1]
  seasonality_period: 48
