data:
  folder_path: data/raw
  years: [2019, 2020, 2021, 2022, 2023, 2024]
  column_name: ND
  max_samples: 1000

split:
  train_size: 0.8
  window_size: 48

model:
  input_size: 1
  hidden_size: 64
  num_layers: 1

training:
  batch_size: 64
  num_epochs: 10
  learning_rate: 0.01

paths:
  model_path: outputs/models/lstm_model.pth
  scaler_path: outputs/models/lstm_scaler.pkl
