dataset: "demand"

paths:
  data_path: "data/processed/demand"
  model_path: "outputs/models/lstm_demand.pt"
  scaler_path: "data/processed/demand/scaler.pkl"
  metrics_path: "outputs/results/lstm_metrics_demand.txt"
  plot_path: "outputs/results/lstm_forecast_demand.png"

model:
  input_size: 1
  hidden_size: 48
  num_layers: 2

training:
  window_size: 48
  batch_size: 128
  num_epochs: 100
  learning_rate: 0.001
  max_training_samples: 2_000
