dataset: "demand"

paths:
  data_path: "data/processed/demand"
  model_path: "outputs/models/lstm_demand.pt"
  scaler_path: "data/processed/demand/scaler.pkl"
  metrics_path: "outputs/results/lstm_metrics_demand.txt"
  plot_path: "outputs/results/lstm_forecast_demand.png"
  prediction_path: "outputs/results/lstm_forecast_demand.csv"

model:
  input_size: 1
  hidden_size: 48
  num_layers: 2
  dropout: 0.1

training:
  window_size: 48
  batch_size: 64
  num_epochs: 200
  learning_rate: 0.0005
  max_training_samples: 0
