dataset: "demand"

paths:
  data_path: "data/processed/demand"
  model_path: "outputs/models/transformer_demand.pt"
  scaler_path: "data/processed/demand/scaler.pkl"
  metrics_path: "outputs/results/transformer_metrics_demand.txt"
  plot_path: "outputs/results/transformer_forecast_demand.png"
  prediction_path: "outputs/results/transformer_forecast_demand.csv"

model:
  input_dim: 1
  feature_size: 48
  num_head: 4
  num_layers: 2
  dropout: 0.1

training:
  window_size: 48
  batch_size: 64
  num_epochs: 50
  learning_rate: 0.0005
  max_training_samples: 0
