data:
  folder_path: data/raw
  years: [2019, 2020, 2021, 2022, 2023, 2024]
  column_name: ND
  max_samples: 5000  # or null to use all data

split:
  train_size: 0.8
  window_size: 10

model:
  input_dim: 1
  feature_size: 250
  num_layers: 1
  dropout: 0.1

training:
  batch_size: 64
  num_epochs: 10
  learning_rate: 0.00005

paths:
  model_path: models/transformer.pt
  scaler_path: models/transformer_scaler.pkl
